<!DOCTYPE html>
<html lang="en">

<html>
	<body>

		<?php
			include 'fizzbuzz.php';

			fizz_buzz(1);
			fizz_buzz(2);
			fizz_buzz(3);
			fizz_buzz(4);
			fizz_buzz(5);
			fizz_buzz(6);
			fizz_buzz(7);
			fizz_buzz(8);
			fizz_buzz(9);
			fizz_buzz(10);
			fizz_buzz(11);
			fizz_buzz(12);
			fizz_buzz(13);
			fizz_buzz(14);
			fizz_buzz(15);
			fizz_buzz(16);
			fizz_buzz(17);
			fizz_buzz(18);
			fizz_buzz(19);
			fizz_buzz(20);
			fizz_buzz(21);
			fizz_buzz(22);
			fizz_buzz(23);
			fizz_buzz(24);
			fizz_buzz(25);
			fizz_buzz(26);
			fizz_buzz(27);
			fizz_buzz(28);
			fizz_buzz(29);
			fizz_buzz(30);
			fizz_buzz(31);
			fizz_buzz(32);
			fizz_buzz(33);
			fizz_buzz(34);
			fizz_buzz(35);
			fizz_buzz(36);
			fizz_buzz(37);
			fizz_buzz(38);
			fizz_buzz(39);
			fizz_buzz(40);
			fizz_buzz(41);
			fizz_buzz(42);
			fizz_buzz(43);
			fizz_buzz(44);
			fizz_buzz(45);
			fizz_buzz(46);
			fizz_buzz(47);
			fizz_buzz(48);
			fizz_buzz(49);
			fizz_buzz(50);
			fizz_buzz(51);
			fizz_buzz(52);
			fizz_buzz(53);
			fizz_buzz(54);
			fizz_buzz(55);
			fizz_buzz(56);
			fizz_buzz(57);
			fizz_buzz(58);
			fizz_buzz(59);
			fizz_buzz(60);
			fizz_buzz(61);
			fizz_buzz(62);
			fizz_buzz(63);
			fizz_buzz(64);
			fizz_buzz(65);
			fizz_buzz(66);
			fizz_buzz(67);
			fizz_buzz(68);
			fizz_buzz(69);
			fizz_buzz(70);
			fizz_buzz(71);
			fizz_buzz(72);
			fizz_buzz(73);
			fizz_buzz(74);
			fizz_buzz(75);
			fizz_buzz(76);
			fizz_buzz(77);
			fizz_buzz(78);
			fizz_buzz(79);
			fizz_buzz(80);
			fizz_buzz(81);
			fizz_buzz(82);
			fizz_buzz(83);
			fizz_buzz(84);
			fizz_buzz(85);
			fizz_buzz(86);
			fizz_buzz(87);
			fizz_buzz(88);
			fizz_buzz(89);
			fizz_buzz(90);
			fizz_buzz(91);
			fizz_buzz(92);
			fizz_buzz(93);
			fizz_buzz(94);
			fizz_buzz(95);
			fizz_buzz(96);
			fizz_buzz(97);
			fizz_buzz(98);
			fizz_buzz(99);
			fizz_buzz(100);

		?>
		
	</body>
</html> 